### PR TITLE
Add AssertJ-DB documentation

### PR DESCRIPTION
**Pull request by VanRoy**
Migrate AssertJ DB documentation from HTML to Markdown

### CODE REVIEW

**Comment by scordio** [comment]
Not in this PR but as a potential follow up, would it make sense to rewrite the diagrams in one of the plain text formats supported by [asciidoctor-diagram](https://asciidoctor.org/docs/asciidoctor-diagram/)?

**Comment by VanRoy** [comment]
@scordio Indeed it's a very good idea, even if some diagram are a little bit complicated 😄 . I will investigate to define wich format is the most adapted and prepare an aditionnal PR with this enhancement. Thanks.

**Comment by scordio** [comment]
I enabled asciidoctor-diagram in d30a83fa19dbde3441e714d5364a340b5d6050fb, feel free to play with it! 🙂

**Comment by VanRoy** [comment]
@scordio Thanks, I will try. Do you think that we can merge this one before to avoid potentials conflicts ?

**Comment by joel-costigliola** [comment]
@VanRoy got for it

**Pull request merged**
